deps: Bump the "quarkus" group with 2 updates across multiple ecosystems (#958)
Bumps the quarkus group with 2 updates:
[io.quarkus:quarkus-bom](https://github.com/quarkusio/quarkus) and
io.quarkus:quarkus-maven-plugin.

Updates `io.quarkus:quarkus-bom` from 3.30.1 to 3.30.2
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/quarkusio/quarkus/releases">io.quarkus:quarkus-bom's
releases</a>.</em></p>
<blockquote>
<h2>3.30.2</h2>
<h3>Complete changelog</h3>
<ul>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/48784">#48784</a>
- Support ephemeral ports in dev services config</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/48815">#48815</a>
- Fix dev service ephemeral ports: Make test resource config override
dev service config and system props</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/50389">#50389</a>
- Testing Lambda resource endpoint with rest-assured and random
test-port results in an IllegalArgumentException</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/50513">#50513</a>
- quarkus-cache with cache.getAsync() does not respect
expire-after-write or expire-after-access</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/50931">#50931</a>
- Make sure that Mutiny can use SR-CP to propagate <code>cancel()</code>
up from <code>CompletableFuture</code></li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51055">#51055</a>
- Upgrade from Hibernate ORM 7.1.6.Final to 7.1.10.Final and from
Hibernate Reactive 3.1.8.Final to 3.1.9.Final</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51116">#51116</a>
- Docs fix: Minor corrections to OpenShift guide based on downstream QE
feedback</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51148">#51148</a>
- Bump narayana-lra.version from 1.0.2.Final to 1.0.3.Final</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51245">#51245</a>
- Docker compose dev services fails on Docker v29</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51247">#51247</a>
- Fix Docker Compose Dev Services NPE on Docker v29</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51254">#51254</a>
- StartupLogCompressor NULL checks</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51266">#51266</a>
- Quarkus maven plugin sometimes fails to acquire maven lock</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51269">#51269</a>
- Re-running failing test fails with classloader errors</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51272">#51272</a>
- Re-try Maven resolver lock acquisition errors with a blocking task
runner</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51280">#51280</a>
- Bump to Mutiny 3.0.3 and Vert.x Mutiny bindings 3.20.4</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51281">#51281</a>
- unable to test with InMemoryConnector after upgrading to 3.30</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51283">#51283</a>
- Improvements on observability docs</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51285">#51285</a>
- java.util.concurrent.ExecutionException:
java.lang.IllegalArgumentException: Duplicate field added thrown during
JUNIT test</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51287">#51287</a>
- OpenAPI: skip adding method references to model without
OperationFilter</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51289">#51289</a>
- Use RoutingContext#normalizedPath() in access log exclusion</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51294">#51294</a>
- Update to UBI 9 9.7</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51298">#51298</a>
- Dispose of the FacadeClassLoader at the end of every test plan so
surefire reruns are tolerated</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51302">#51302</a>
- Bump org.hibernate.tool:hibernate-tools-language from 7.1.6.Final to
7.1.10.Final in the hibernate group across 1 directory</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51304">#51304</a>
- Update version of jandex gradle plugin in docs</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51305">#51305</a>
- Update documentation to point to Jandex Gradle 2.3.0</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51308">#51308</a>
- Dev MCP: Reduce the payload for the extension list call</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51309">#51309</a>
- Make messaging channel connector and enabled config properties runtime
(again)</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51311">#51311</a>
- ArC: guard against multiple occurrences of the same decorator</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51335">#51335</a>
- Fix typo</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/quarkusio/quarkus/commit/6a141cd4c288d83cca2057b856007680e573498f"><code>6a141cd</code></a>
[RELEASE] - Bump version to 3.30.2</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/8fcbcddfd80b1ed64b51eaca7d7706a79822f91e"><code>8fcbcdd</code></a>
ArC: guard against multiple occurrences of the same decorator</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/8e094e7a02147681c45c74470041c8b6d69887b0"><code>8e094e7</code></a>
Merge pull request <a
href="https://redirect.github.com/quarkusio/quarkus/issues/51343">#51343</a>
from gsmet/3.30.2-backports-1</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/b9e15b26a65be39891b3e4056d1ff0ff65441ff8"><code>b9e15b2</code></a>
Fix typo</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/bbe5179fc9520f6e2870b351fbc0bbecbe9b3618"><code>bbe5179</code></a>
Make messaging channel connector and enabled config properties runtime
again</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/c91d86df9487c1e03d307fa5304cbb52478ffacc"><code>c91d86d</code></a>
Update to UBI 9 9.7</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/ad888f6668d8fd595657fa8ac6194d3675bd19c9"><code>ad888f6</code></a>
revert removal of 3.2 note</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/f40254bdcf1412063eef9ae1f9669196c9e7d33c"><code>f40254b</code></a>
implement downstream QE fixes upstream</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/68a1402fb63fd64f7627d5b2124b916f1e58638f"><code>68a1402</code></a>
OpenAPI: skip adding method references to model without
OperationFilter</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/fbdeed7fc037590379c5e72e079391d7147fd691"><code>fbdeed7</code></a>
Improvements on observability docs</li>
<li>Additional commits viewable in <a
href="https://github.com/quarkusio/quarkus/compare/3.30.1...3.30.2">compare
view</a></li>
</ul>
</details>
<br />

Updates `io.quarkus:quarkus-maven-plugin` from 3.30.1 to 3.30.2

Updates `io.quarkus:quarkus-maven-plugin` from 3.30.1 to 3.30.2

Bumps the quarkus group with 2 updates:
[io.quarkus:quarkus-bom](https://github.com/quarkusio/quarkus) and
io.quarkus.

Updates `io.quarkus:quarkus-bom` from 3.30.1 to 3.30.2
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/quarkusio/quarkus/releases">io.quarkus:quarkus-bom's
releases</a>.</em></p>
<blockquote>
<h2>3.30.2</h2>
<h3>Complete changelog</h3>
<ul>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/48784">#48784</a>
- Support ephemeral ports in dev services config</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/48815">#48815</a>
- Fix dev service ephemeral ports: Make test resource config override
dev service config and system props</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/50389">#50389</a>
- Testing Lambda resource endpoint with rest-assured and random
test-port results in an IllegalArgumentException</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/50513">#50513</a>
- quarkus-cache with cache.getAsync() does not respect
expire-after-write or expire-after-access</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/50931">#50931</a>
- Make sure that Mutiny can use SR-CP to propagate <code>cancel()</code>
up from <code>CompletableFuture</code></li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51055">#51055</a>
- Upgrade from Hibernate ORM 7.1.6.Final to 7.1.10.Final and from
Hibernate Reactive 3.1.8.Final to 3.1.9.Final</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51116">#51116</a>
- Docs fix: Minor corrections to OpenShift guide based on downstream QE
feedback</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51148">#51148</a>
- Bump narayana-lra.version from 1.0.2.Final to 1.0.3.Final</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51245">#51245</a>
- Docker compose dev services fails on Docker v29</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51247">#51247</a>
- Fix Docker Compose Dev Services NPE on Docker v29</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51254">#51254</a>
- StartupLogCompressor NULL checks</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51266">#51266</a>
- Quarkus maven plugin sometimes fails to acquire maven lock</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51269">#51269</a>
- Re-running failing test fails with classloader errors</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51272">#51272</a>
- Re-try Maven resolver lock acquisition errors with a blocking task
runner</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51280">#51280</a>
- Bump to Mutiny 3.0.3 and Vert.x Mutiny bindings 3.20.4</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51281">#51281</a>
- unable to test with InMemoryConnector after upgrading to 3.30</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51283">#51283</a>
- Improvements on observability docs</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51285">#51285</a>
- java.util.concurrent.ExecutionException:
java.lang.IllegalArgumentException: Duplicate field added thrown during
JUNIT test</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51287">#51287</a>
- OpenAPI: skip adding method references to model without
OperationFilter</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51289">#51289</a>
- Use RoutingContext#normalizedPath() in access log exclusion</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51294">#51294</a>
- Update to UBI 9 9.7</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51298">#51298</a>
- Dispose of the FacadeClassLoader at the end of every test plan so
surefire reruns are tolerated</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51302">#51302</a>
- Bump org.hibernate.tool:hibernate-tools-language from 7.1.6.Final to
7.1.10.Final in the hibernate group across 1 directory</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51304">#51304</a>
- Update version of jandex gradle plugin in docs</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51305">#51305</a>
- Update documentation to point to Jandex Gradle 2.3.0</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51308">#51308</a>
- Dev MCP: Reduce the payload for the extension list call</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51309">#51309</a>
- Make messaging channel connector and enabled config properties runtime
(again)</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51311">#51311</a>
- ArC: guard against multiple occurrences of the same decorator</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51335">#51335</a>
- Fix typo</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/quarkusio/quarkus/commit/6a141cd4c288d83cca2057b856007680e573498f"><code>6a141cd</code></a>
[RELEASE] - Bump version to 3.30.2</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/8fcbcddfd80b1ed64b51eaca7d7706a79822f91e"><code>8fcbcdd</code></a>
ArC: guard against multiple occurrences of the same decorator</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/8e094e7a02147681c45c74470041c8b6d69887b0"><code>8e094e7</code></a>
Merge pull request <a
href="https://redirect.github.com/quarkusio/quarkus/issues/51343">#51343</a>
from gsmet/3.30.2-backports-1</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/b9e15b26a65be39891b3e4056d1ff0ff65441ff8"><code>b9e15b2</code></a>
Fix typo</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/bbe5179fc9520f6e2870b351fbc0bbecbe9b3618"><code>bbe5179</code></a>
Make messaging channel connector and enabled config properties runtime
again</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/c91d86df9487c1e03d307fa5304cbb52478ffacc"><code>c91d86d</code></a>
Update to UBI 9 9.7</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/ad888f6668d8fd595657fa8ac6194d3675bd19c9"><code>ad888f6</code></a>
revert removal of 3.2 note</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/f40254bdcf1412063eef9ae1f9669196c9e7d33c"><code>f40254b</code></a>
implement downstream QE fixes upstream</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/68a1402fb63fd64f7627d5b2124b916f1e58638f"><code>68a1402</code></a>
OpenAPI: skip adding method references to model without
OperationFilter</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/fbdeed7fc037590379c5e72e079391d7147fd691"><code>fbdeed7</code></a>
Improvements on observability docs</li>
<li>Additional commits viewable in <a
href="https://github.com/quarkusio/quarkus/compare/3.30.1...3.30.2">compare
view</a></li>
</ul>
</details>
<br />

Updates `io.quarkus` from 3.30.1 to 3.30.2


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>