deps: Bump the "quarkus" group with 2 updates across multiple ecosystems (#962)
Bumps the quarkus group with 2 updates:
[io.quarkus:quarkus-bom](https://github.com/quarkusio/quarkus) and
io.quarkus.

Updates `io.quarkus:quarkus-bom` from 3.30.2 to 3.30.3
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/quarkusio/quarkus/releases">io.quarkus:quarkus-bom's
releases</a>.</em></p>
<blockquote>
<h2>3.30.3</h2>
<h3>Complete changelog</h3>
<ul>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/50298">#50298</a>
- Call to the
<code>jakarta.data.repository.BasicRepository#saveAll</code> results in
NPE after Hibernate ORM bump to 7.1.1.Final</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/50919">#50919</a>
- Java classes generated by <code>wsdl2java</code> not passed to Gradle
<code>compileKotlin</code> since 3.26.1</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51044">#51044</a>
- JavaDoc not rendering correctly</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51290">#51290</a>
- Add cross-references between CSRF and CORS filter</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51339">#51339</a>
- Enhance error message when
quarkus.hibernate-search-orm.management.enabled=true is enabled but no
quarkus-vertx-http defined</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51340">#51340</a>
- Fix JavaDoc for quarkus.management.enabled</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51341">#51341</a>
- Use correct name for <code>org.graalvm.sdk:nativebridge</code>
dependency</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51344">#51344</a>
- Set expiresIn to one hour for OIDC Dev Services</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51345">#51345</a>
- extraneous semicolon in LGTM starter</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51346">#51346</a>
- Bump the hibernate group with 9 updates</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51352">#51352</a>
- Bump org.quartz-scheduler:quartz from 2.5.0 to 2.5.2</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51358">#51358</a>
- Bump Keycloak version to 26.4.7</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51361">#51361</a>
- Remove extraneous semicolon in LGTM codestart</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51370">#51370</a>
- Add documentation about <code>@JsonView</code> support in the REST
Client</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51372">#51372</a>
- Make token expiration configurable for OIDC Dev Services</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51375">#51375</a>
- Config relocation mp.messaging -&gt; quarkus.messaging
relocation/fallback</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51376">#51376</a>
- Bump kafka.version from 4.0.1 to 4.1.1</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51377">#51377</a>
- Enhance docs for quarkus.debug.reflection option</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51378">#51378</a>
- QuarkusComponentTest fails with ambiguous dependencies if bean is
injected with parameterized qualifier multiple times</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51379">#51379</a>
- Check that Vert.x HTTP is available before enabling Hibernate Search
management endpoints</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51380">#51380</a>
- Clear some internal state of REST Assured between tests</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51394">#51394</a>
- Make container-image.tag optional so it is possible to nullify it</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51399">#51399</a>
- Fix LogRuntimeConfig doc rendering</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51408">#51408</a>
- Lambda extension: Failed to start quarkus because of
NoSuchMethodError</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51410">#51410</a>
- Merge LambdaConfig with same FQN</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51416">#51416</a>
- Bump wildfly-elytron.version from 2.7.0.Final to 2.7.1.Final</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51418">#51418</a>
- Added cross references between CORS and CSRF guides</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51424">#51424</a>
- Add missing imports to Decorator example in cdi.adoc</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51431">#51431</a>
- Error running Quarkus: java.lang.ExceptionInInitializerError &gt;
<code>@POST</code> with Record</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51440">#51440</a>
- In Gradle, change compilation tasks' source dirs to their parent</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51442">#51442</a>
- QuarkusComponentTest: remove duplicate unsatisfied injection
points</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51447">#51447</a>
- Update the extension guide to rename enable to enabled</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51453">#51453</a>
- Make sure we don't accept unannotated parameters for records</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/quarkusio/quarkus/commit/b4ab1980e00a40d41787e2e563cad263ca24961c"><code>b4ab198</code></a>
[RELEASE] - Bump version to 3.30.3</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/bb797e2a6f86c43f6d49d519818a7a443e5c9f09"><code>bb797e2</code></a>
Merge pull request <a
href="https://redirect.github.com/quarkusio/quarkus/issues/51479">#51479</a>
from gsmet/3.30.3-backports-1</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/9a7110365baaf9e23bc4457c2883ba57fca2eaf2"><code>9a71103</code></a>
docs: rename 'enable' to 'enabled'</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/dfb0ac9bdf45a87d07959e8a85e60668f8eefb17"><code>dfb0ac9</code></a>
Make sure we don't accept unannotated parameters for records</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/b16dcf24a68065c50e0c8f5c839d7b4f893e516d"><code>b16dcf2</code></a>
Added cross references between CORS and CSRF guides</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/e6feecbee072a30bfb2609b68350aca36acb4d0b"><code>e6feecb</code></a>
QuarkusComponentTest: remove duplicate unsatisfied injection points</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/35b5f12e2d8b5af594e3e606f4a57018bbd4a4c9"><code>35b5f12</code></a>
Use correct name for org.graalvm.sdk:nativebrdige dependency</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/f9fa64b53c0c56943b7d9d6d89e8e69e7e8d5427"><code>f9fa64b</code></a>
Make container-image.tag optional so it is possible to nullify it</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/efb6c4f4dd14b8724dd8f171027cdfaf7ed3db3a"><code>efb6c4f</code></a>
Bump the hibernate group with 9 updates</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/272efbe63328a6540f779f7f5192246660ed57aa"><code>272efbe</code></a>
In Gradle, change compilation tasks' source dirs to their parent</li>
<li>Additional commits viewable in <a
href="https://github.com/quarkusio/quarkus/compare/3.30.2...3.30.3">compare
view</a></li>
</ul>
</details>
<br />

Updates `io.quarkus` from 3.30.2 to 3.30.3

Bumps the quarkus group with 2 updates:
[io.quarkus:quarkus-bom](https://github.com/quarkusio/quarkus) and
io.quarkus:quarkus-maven-plugin.

Updates `io.quarkus:quarkus-bom` from 3.30.2 to 3.30.3
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/quarkusio/quarkus/releases">io.quarkus:quarkus-bom's
releases</a>.</em></p>
<blockquote>
<h2>3.30.3</h2>
<h3>Complete changelog</h3>
<ul>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/50298">#50298</a>
- Call to the
<code>jakarta.data.repository.BasicRepository#saveAll</code> results in
NPE after Hibernate ORM bump to 7.1.1.Final</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/50919">#50919</a>
- Java classes generated by <code>wsdl2java</code> not passed to Gradle
<code>compileKotlin</code> since 3.26.1</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51044">#51044</a>
- JavaDoc not rendering correctly</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51290">#51290</a>
- Add cross-references between CSRF and CORS filter</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51339">#51339</a>
- Enhance error message when
quarkus.hibernate-search-orm.management.enabled=true is enabled but no
quarkus-vertx-http defined</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51340">#51340</a>
- Fix JavaDoc for quarkus.management.enabled</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51341">#51341</a>
- Use correct name for <code>org.graalvm.sdk:nativebridge</code>
dependency</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51344">#51344</a>
- Set expiresIn to one hour for OIDC Dev Services</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51345">#51345</a>
- extraneous semicolon in LGTM starter</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51346">#51346</a>
- Bump the hibernate group with 9 updates</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51352">#51352</a>
- Bump org.quartz-scheduler:quartz from 2.5.0 to 2.5.2</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51358">#51358</a>
- Bump Keycloak version to 26.4.7</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51361">#51361</a>
- Remove extraneous semicolon in LGTM codestart</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51370">#51370</a>
- Add documentation about <code>@JsonView</code> support in the REST
Client</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51372">#51372</a>
- Make token expiration configurable for OIDC Dev Services</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51375">#51375</a>
- Config relocation mp.messaging -&gt; quarkus.messaging
relocation/fallback</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51376">#51376</a>
- Bump kafka.version from 4.0.1 to 4.1.1</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51377">#51377</a>
- Enhance docs for quarkus.debug.reflection option</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51378">#51378</a>
- QuarkusComponentTest fails with ambiguous dependencies if bean is
injected with parameterized qualifier multiple times</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51379">#51379</a>
- Check that Vert.x HTTP is available before enabling Hibernate Search
management endpoints</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51380">#51380</a>
- Clear some internal state of REST Assured between tests</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51394">#51394</a>
- Make container-image.tag optional so it is possible to nullify it</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51399">#51399</a>
- Fix LogRuntimeConfig doc rendering</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51408">#51408</a>
- Lambda extension: Failed to start quarkus because of
NoSuchMethodError</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51410">#51410</a>
- Merge LambdaConfig with same FQN</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51416">#51416</a>
- Bump wildfly-elytron.version from 2.7.0.Final to 2.7.1.Final</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51418">#51418</a>
- Added cross references between CORS and CSRF guides</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51424">#51424</a>
- Add missing imports to Decorator example in cdi.adoc</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/issues/51431">#51431</a>
- Error running Quarkus: java.lang.ExceptionInInitializerError &gt;
<code>@POST</code> with Record</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51440">#51440</a>
- In Gradle, change compilation tasks' source dirs to their parent</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51442">#51442</a>
- QuarkusComponentTest: remove duplicate unsatisfied injection
points</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51447">#51447</a>
- Update the extension guide to rename enable to enabled</li>
<li><a
href="https://redirect.github.com/quarkusio/quarkus/pull/51453">#51453</a>
- Make sure we don't accept unannotated parameters for records</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/quarkusio/quarkus/commit/b4ab1980e00a40d41787e2e563cad263ca24961c"><code>b4ab198</code></a>
[RELEASE] - Bump version to 3.30.3</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/bb797e2a6f86c43f6d49d519818a7a443e5c9f09"><code>bb797e2</code></a>
Merge pull request <a
href="https://redirect.github.com/quarkusio/quarkus/issues/51479">#51479</a>
from gsmet/3.30.3-backports-1</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/9a7110365baaf9e23bc4457c2883ba57fca2eaf2"><code>9a71103</code></a>
docs: rename 'enable' to 'enabled'</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/dfb0ac9bdf45a87d07959e8a85e60668f8eefb17"><code>dfb0ac9</code></a>
Make sure we don't accept unannotated parameters for records</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/b16dcf24a68065c50e0c8f5c839d7b4f893e516d"><code>b16dcf2</code></a>
Added cross references between CORS and CSRF guides</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/e6feecbee072a30bfb2609b68350aca36acb4d0b"><code>e6feecb</code></a>
QuarkusComponentTest: remove duplicate unsatisfied injection points</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/35b5f12e2d8b5af594e3e606f4a57018bbd4a4c9"><code>35b5f12</code></a>
Use correct name for org.graalvm.sdk:nativebrdige dependency</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/f9fa64b53c0c56943b7d9d6d89e8e69e7e8d5427"><code>f9fa64b</code></a>
Make container-image.tag optional so it is possible to nullify it</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/efb6c4f4dd14b8724dd8f171027cdfaf7ed3db3a"><code>efb6c4f</code></a>
Bump the hibernate group with 9 updates</li>
<li><a
href="https://github.com/quarkusio/quarkus/commit/272efbe63328a6540f779f7f5192246660ed57aa"><code>272efbe</code></a>
In Gradle, change compilation tasks' source dirs to their parent</li>
<li>Additional commits viewable in <a
href="https://github.com/quarkusio/quarkus/compare/3.30.2...3.30.3">compare
view</a></li>
</ul>
</details>
<br />

Updates `io.quarkus:quarkus-maven-plugin` from 3.30.2 to 3.30.3

Updates `io.quarkus:quarkus-maven-plugin` from 3.30.2 to 3.30.3


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>